Repository Team-Inframe/Inframe-Backend, pull requests merged in 2025-01, with the labels that each got.

#2 [chore] 개발 환경 세팅
  .gitignore
  Dockerfile
  config/__init__.py
  config/asgi.py
  config/settings.py
  config/urls.py
  config/wsgi.py
  docker-compose.yml
  manage.py
  requirements.txt
Labels: 🪄 Chore

#4 [chore] MySQL 도커 세팅
  .github/PULL_REQUEST_TEMPLATE.md
  config/settings.py
  docker-compose.yml
  requirements.txt
  wait-for-it.sh
Labels: 🪄 Chore

#6 [test] 세팅 가이드
  config/settings.py
  config/urls.py
  sticker/__init__.py
  sticker/admin.py
  sticker/apps.py
  sticker/migrations/__init__.py
  sticker/models.py
  sticker/tests.py
  sticker/urls.py
  sticker/views.py
Labels: 📝 Test

#10 [chore] Amazon RDS, S3 연결
  config/settings.py
  config/urls.py
  docker-compose.yml
  requirements.txt
Labels: 🪄 Chore

#12 [feat] 초기 프레임 생성 기능 구현
  config/settings.py
  config/urls.py
  frame/__init__.py
  frame/admin.py
  frame/apps.py
  frame/migrations/0001_initial.py
  frame/migrations/0002_alter_frame_camera_height_alter_frame_camera_width.py
  frame/migrations/0003_rename_camera_height_frame_cameraheight_and_more.py
  frame/migrations/__init__.py
  frame/models.py
  frame/s3_utils.py
  frame/serializers.py
  frame/tests.py
  frame/urls.py
  frame/views.py
  requirements.txt
Labels: 🚀 Feat

#14 [feat] 회원가입, 로그인 기능 구현
  config/settings.py
  config/urls.py
  docker-compose.yml
  requirements.txt
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_rename_created_at_user_createdat_and_more.py
  user/migrations/0003_alter_user_table.py
  user/migrations/0004_rename_userid_user_id.py
  user/migrations/__init__.py
  user/models.py
  user/serializer.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: 🚀 Feat

#15 [feat] 스티커 api 생성
  config/urls.py
  requirements.txt
  sticker/migrations/0001_initial.py
  sticker/models.py
  sticker/serializer.py
  sticker/views.py
Labels: 🚀 Feat

#20 [feat] 커스텀 프레임 모델링 구현
  config/settings.py
  config/urls.py
  custom_frame/__init__.py
  custom_frame/admin.py
  custom_frame/apps.py
  custom_frame/migrations/__init__.py
  custom_frame/models.py
  custom_frame/serializer.py
  custom_frame/tests.py
  custom_frame/urls.py
  custom_frame/views.py
Labels: 🚀 Feat

#22 [feat] ai 배경 생성 기능 구현
  frame/serializers.py
  frame/urls.py
  frame/views.py
  sticker/migrations/0002_sticker_userid.py
  sticker/migrations/0003_remove_sticker_userid.py
  sticker/models.py
  sticker/views.py
Labels: 🚀 Feat

#25 [feat] 최종 사진본 생성 기능 구현
  config/settings.py
  config/urls.py
  custom_frame/migrations/0001_initial.py
  custom_frame/models.py
  custom_frame/views.py
  photo/__init__.py
  photo/admin.py
  photo/apps.py
  photo/migrations/0001_initial.py
  photo/migrations/0002_alter_photo_userid.py
  photo/migrations/0003_alter_photo_photourl.py
  photo/migrations/0004_alter_photo_userid.py
  photo/migrations/0005_alter_photo_userid.py
  photo/migrations/0006_alter_photo_userid.py
  photo/migrations/__init__.py
  photo/models.py
  photo/serializer.py
  photo/tests.py
  photo/urls.py
  photo/views.py
  sticker/migrations/0004_sticker_userid.py
  sticker/migrations/0005_alter_sticker_userid.py
  sticker/migrations/0006_alter_sticker_userid.py
  sticker/models.py
  sticker/serializer.py
  sticker/views.py
Labels: 🚀 Feat

#27 [feat] 커스텀 프레임 조회 기능 구현
  config/urls.py
  custom_frame/urls.py
  custom_frame/view2.py
Labels: 🚀 Feat

#30 [feat] 내가 만든 커스텀 프레임 목록 조회
  custom_frame/migrations/0002_rename_createdat_customframe_created_at_and_more.py
  custom_frame/models.py
  custom_frame/urls.py
  custom_frame/view2.py
Labels: 🚀 Feat

#32 feat: 갤러리 목록 조회 기능 구현
  custom_frame/migrations/0002_rename_createdat_customframe_created_at_and_more.py
  custom_frame/migrations/0003_rename_custom_frame_customframe_custom_frame_id.py
  custom_frame/models.py
  frame/migrations/0005_rename_cameraheight_frame_camera_height_and_more.py
  frame/migrations/0006_rename_id_frame_frame.py
  frame/migrations/0007_rename_frame_frame_frame_id.py
  frame/models.py
  frame/serializers.py
  frame/urls.py
  frame/views.py
  photo/migrations/0007_rename_createdat_photo_created_at_and_more.py
  photo/migrations/0008_rename_photo_id_photo_photo_and_more.py
  photo/migrations/0009_rename_photo_photo_photo_id.py
  photo/models.py
  photo/serializer.py
  photo/urls.py
  photo/views.py
  sticker/migrations/0007_rename_createdat_sticker_created_at_and_more.py
  sticker/migrations/0008_alter_sticker_user_id.py
  sticker/migrations/0009_rename_id_sticker_sticker_and_more.py
  sticker/migrations/0010_alter_sticker_user.py
  sticker/migrations/0011_rename_sticker_sticker_sticker_id.py
  sticker/models.py
  sticker/serializer.py
  sticker/views.py
  user/migrations/0005_rename_createdat_user_created_at_and_more.py
  user/migrations/0006_rename_id_user_user.py
  user/migrations/0007_rename_user_user_user_id.py
  user/models.py
  user/views.py
Labels: 🚀 Feat

#33 [feat] 커스텀 프레임 생성 기능 구현
  custom_frame/migrations/0004_customframesticker.py
  custom_frame/models.py
  custom_frame/s3_utils.py
  custom_frame/urls.py
  custom_frame/views1.py
Labels: 🚀 Feat

#36 [feat] 내가 저장한 커스텀 프레임 목록 조회
  custom_frame/serializer.py
  custom_frame/urls.py
  custom_frame/view2.py
  custom_frame/views.py
Labels: 🚀 Feat

#38 [feat] 커스텀 프레임 전체 목록 조회 기능 구현
  custom_frame/migrations/0005_customframe_bookmarks.py
  custom_frame/models.py
  custom_frame/urls.py
  custom_frame/views1.py
Labels: 🚀 Feat

#41 [feat] 북마크 기능 구현
  custom_frame/migrations/0006_bookmark.py
  custom_frame/models.py
  custom_frame/serializer.py
  custom_frame/urls.py
  custom_frame/view2.py
Labels: 🚀 Feat

#43 [feat] 내가 만든 커스텀 프레임 목록 조회
  custom_frame/models.py
  custom_frame/urls.py
  custom_frame/view2.py
  frame/urls.py
Labels: 🚀 Feat

#47 [fix] traefik 인증서 오류 해결
  docker-compose-prod.yml
Labels: 🔨 Fix

#48 [Refactor] 코드 전반 리팩토링 및 정리
  config/settings.py
  custom_frame/models.py
  custom_frame/urls.py
  custom_frame/view2.py
  custom_frame/views1.py
  frame/views.py
  photo/views.py
  requirements.txt
Labels: 🧠 Refactor

#54 [refactor] 목록 조회 응답 데이터 변경
  custom_frame/models.py
  custom_frame/serializer.py
  custom_frame/view2.py
  photo/views.py
Labels: 🧠 Refactor

#58 [deploy] 메인 브랜치로 배포
  config/settings.py
  custom_frame/models.py
  custom_frame/serializer.py
  custom_frame/urls.py
  custom_frame/view2.py
  custom_frame/views1.py
  frame/views.py
  photo/views.py
  requirements.txt
Labels: 🌎 Deploy

#57 [feat] endpoint 수정
  config/urls.py
  custom_frame/urls.py
  frame/urls.py
  photo/urls.py
  sticker/views.py
  user/urls.py
Labels: 🚀 Feat

#60 [deploy] 서버 배포
  config/urls.py
  custom_frame/urls.py
  frame/urls.py
  photo/urls.py
  sticker/views.py
  user/urls.py
Labels: 🌎 Deploy

#64 [Chore] 도커 항시 빌드 기능 추가
  docker-compose.yml
Labels: 🪄 Chore

#63 [feat] s3 업로드 경로 수정
  config/settings.py
  config/urls.py
  custom_frame/urls.py
  custom_frame/views1.py
  docker-compose.yml
  frame/urls.py
  frame/views.py
  photo/urls.py
  user/urls.py
Labels: 🚀 Feat

#66 [chore] CI/CD 파이프라인 구축
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  docker-compose.yml
Labels: 🪄 Chore

#67 [test] cd 테스트
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  config/settings.py
  config/urls.py
  custom_frame/urls.py
  custom_frame/views1.py
  docker-compose-prod.yml
  docker-compose.yml
  frame/urls.py
  frame/views.py
  photo/urls.py
  user/urls.py
Labels: 🌎 Deploy, 📝 Test

#69 [chore] cd 파이프라인 수정
  .github/workflows/cd.yml
  docker-compose-prod.yml
Labels: 🪄 Chore

#70 [test] cd 테스트
  .github/workflows/cd.yml
  docker-compose-prod.yml
Labels: 🌎 Deploy

#71 [test] cd 테스트
  .github/workflows/cd.yml
Labels: 📝 Test

#72 [test] cd 테스트
  custom_frame/models.py
Labels: 📝 Test

#74 [test] script 수정
  .github/workflows/cd.yml
Labels: 📝 Test

#75 [fix] cd 오류 해결
  .github/workflows/cd.yml
Labels: 🌎 Deploy, 🔨 Fix

#76 [chore] RabbitMQ + Celery 세팅
  config/__init__.py
  config/celery.py
  config/settings.py
  docker-compose-prod.yml
  docker-compose.yml
  requirements.txt
  sticker/tasks.py
Labels: 🪄 Chore

#78 [fix] 특정 이미지 모델 조건 추가
  docker-compose-prod.yml
  frame/models.py
  frame/views.py
Labels: 🔨 Fix

#79 [deploy] 서버 배포
  config/__init__.py
  config/celery.py
  config/settings.py
  docker-compose-prod.yml
  docker-compose.yml
  frame/models.py
  frame/views.py
  requirements.txt
  sticker/tasks.py
Labels: 🌎 Deploy

#80 [fix] 네트워크 설정 추가
  docker-compose-prod.yml
Labels: 🌎 Deploy, 🔨 Fix

#81 hotfix: 경로 수정
  docker-compose-prod.yml
Labels: 🔨 Fix

#82 [test] 주석 처리
  docker-compose-prod.yml
Labels: 📝 Test

#84 [feat] bookmarks 응답값 추가
  custom_frame/view2.py
  docker-compose-prod.yml
Labels: 🚀 Feat

#86 [feat] 북마크 삭제 기능 구현
  custom_frame/view2.py
Labels: 🚀 Feat

#88 [feat] 스티커 목록 조회 api 구현
  sticker/urls.py
  sticker/views.py
Labels: 🚀 Feat

#90 [feat] 북마크 여부 응답값 추가
  custom_frame/view2.py
Labels: 🚀 Feat

#93 [feat] api 응답값 수정
  custom_frame/view2.py
  docker-compose-prod.yml
  frame/migrations/0008_frame_basic_frame_id_frame_frame_bg.py
  frame/models.py
  frame/serializers.py
  frame/views.py
Labels: 🚀 Feat

#95 [feat] 공유 여부에 따른 목록 조회
  custom_frame/view2.py
  custom_frame/views.py
  custom_frame/views1.py
Labels: 🚀 Feat

#97 [feat] api 응답값 수정
  custom_frame/views.py
  frame/migrations/0009_remove_frame_camera_height_remove_frame_camera_width.py
  frame/models.py
  frame/serializers.py
  frame/views.py
Labels: 🚀 Feat

#103 [feat] 회원가입, 로그인 api 닉네임 추가
  user/migrations/0008_user_username.py
  user/migrations/0009_alter_user_username.py
  user/models.py
  user/serializer.py
  user/views.py
Labels: 🚀 Feat

#104 [chore] 배포 환경에서 redis 적용
  config/settings.py
  docker-compose-prod.yml
  docker-compose.yml
Labels: 🪄 Chore

#105 [deploy] 브랜치 develop에서 main으로 병합
  config/settings.py
  docker-compose-prod.yml
  docker-compose.yml
  user/migrations/0008_user_username.py
  user/migrations/0009_alter_user_username.py
  user/models.py
  user/serializer.py
  user/views.py
Labels: 🌎 Deploy

#108 [feat] cloudfront 연결
  config/settings.py
  config/utils.py
Labels: 🚀 Feat

#109 [chore] 배포환경에서 rabbitmq, celery 연동
  config/settings.py
  docker-compose-prod.yml
Labels: 🪄 Chore

#113 [deploy] 메인브랜치로 병합
  config/settings.py
  docker-compose-prod.yml
Labels: 🌎 Deploy

#118 [feat] 사진 단일 조회 기능 추가
  config/urls.py
  docker-compose-prod.yml
  photo/urls.py
  photo/views.py
Labels: 🚀 Feat

#122 [feat] 최종사진 단일 조회
  docker-compose-prod.yml
  frame/views.py
  photo/views.py
Labels: 🚀 Feat

#124 [feat] 배경 프롬프트 수정
  frame/views.py
Labels: 🚀 Feat

#127 [feat] 모든 목록 조회 최신순 기능 추가
  custom_frame/views.py
  photo/views.py
Labels: 🚀 Feat

#129 [feat] 커스텀프레임 생성 기능에서 북마크, 삭제 여부 제거
  custom_frame/views.py
Labels: 🚀 Feat

#136 [feat] 커스텀 프레임 이미지 업로드 api
  custom_frame/models.py
  custom_frame/urls.py
  custom_frame/views.py
Labels: 🚀 Feat

#139 [feat] 날씨 프레임 조회 기능 구현
  custom_frame/urls.py
  custom_frame/views.py
Labels: 🚀 Feat

#142 [feat] 스티커 최신순 정렬
  sticker/views.py
Labels: 🚀 Feat

#144 [feat] 스티커 프롬프트 수정
  docker-compose-prod.yml
  sticker/views.py
Labels: 🚀 Feat

#146 [feat] 스티커 생성 API 응답 수정
  sticker/views.py
Labels: 🚀 Feat

#147 [deploy] 메인 브랜치로 합병
  docker-compose-prod.yml
  sticker/views.py
Labels: 🌎 Deploy

#149 [feat] 도커이미지수정
  docker-compose-prod.yml
Labels: 🚀 Feat

#150 [deploy] 메인 브랜치로 합병
  docker-compose-prod.yml
Labels: 🌎 Deploy

#152 [feat] url 수정
  config/urls.py
  custom_frame/urls.py
  frame/urls.py
  photo/urls.py
  sticker/urls.py
  user/urls.py
Labels: 🚀 Feat
